# Generated by Django 4.1.6 on 2023-02-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BernLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Enter the date in the format: DD/MM/YYYY', verbose_name='Date')),
                ('action', models.CharField(choices=[('BI', 'Backup Intervention'), ('CD', 'Change Disk'), ('RE', 'Restore'), ('OT', 'Other Action')], default='BI', max_length=2)),
                ('comments', models.TextField()),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
    ]
